baseURL: https://github.com/zmdtea/zmdtea.github.io/
languageCode: en-us
defaultContentLanguage: en
title: cupoftea
theme: cupper-hugo-theme
googleAnalytics: UA-123456789-1
disqusShortname: zmdtea
enableGitInfo: false

taxonomies:
  tag: tags

permalinks:
  post: /:filename/

imaging:
  quality: 99

params:
  description: Living Among The Clouds
  homeMetaContent: Living Among The Clouds
  footer: Copyright © 2023 Cup Of Tea
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat: Mar 23, 2023
  codePenUser: zmdtea
  katex: true
  hideHeaderLinks: false
  search: true
  showThemeSwitcher: true
  defaultDarkTheme: false
  moveFooterToHeader: false
  # navTitleText: Cupper Theme
  logoAlt: Cup Of Tea Logo
  customCss:
    - css/custom_01.css
    - css/custom_02.css
  customJs:
    - js/custom_01.js
    - js/custom_02.js
  utterances:
    repo: zmdtea/zmdtea.github.io
    issueTerm: title
    theme: github-light

menu:
  nav:
    - name: Home
      url: /
      weight: 1
    - name: Blog
      url: /post/
      weight: 2
    - name: Tags
      url: /tags/
      weight: 3
    - name: About
      url: /about/
      weight: 4
    - name: Contact
      url: /contact/
      weight: 5

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2


